package org.example.enums;

public enum AdminOptions {
    MODIFY_RESTAURANT,
    VIEW_ALL_RESERVATIONS,
    VIEW_ALL_ORDERS,
    VIEW_ALL_EMPLOYEES,
    VIEW_ALL_TABLES,
    VIEW_ALL_PRODUCTS,
    VIEW_RESTAURANT_DETAILS,
    EXIT
}
